name: Duplicate Discover Weekly playlists

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_21_*_*_MON
    - cron: "0 21 * * MON" # "Every Monday evening."

env:
  SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
  SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
  SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
  DW_EMIL: ${{ vars.DW_EMIL }}
  DW_HALLIS: ${{ vars.DW_HALLIS }}
  DW_EVGENIA: ${{ vars.DW_EVGENIA }}
  DW_MATHIAS: ${{ vars.DW_MATHIAS }}
  DW_CHRISTIAN: ${{ vars.DW_CHRISTIAN }}

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -V
          PY=$(which python)
          echo $PY
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install --dev --deploy --python $PY

      - name: Run python script to duplicate Discover Weekly playlists
        run: python -m pipenv run python discover_weekly.py
